- name: Create a folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    password: nawaz123
    url: http://172.31.13.91:8080
    user: nawaz990
  loop:
    - CI-Pipelines


- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/s-pipeline.xml') }}"
    name: "CI-Pipelines/{{item}}"
    password: nawaz123
    url: http://172.31.13.91:8080
    user: nawaz990
  loop:
    - frontend
    - catalogue
    - cart
    - user
    - shipping
    - payment


