- name: Create a folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    password: nawaz123
    url: http://172.31.13.91:8080
    user: nawaz990
  loop:
    - CI-Pipelines

- name: Include Pipeline tasks
  ansible.builtin.include_tasks: s-pipeline.yml
  vars:
    COMPONENT: "{{item}}"
  loop:
    - frontend
    - catalogue
    - cart
    - user
    - shipping
    - payment



